syntax = "proto3";

package SimPitchProtos.SimulationService.SimulationEngine;


import "SimulationEngine/requests.proto";
import "SimulationEngine/responses.proto";
import "commonTypes.proto";
import "google/protobuf/empty.proto";

option csharp_namespace = "SimPitchProtos.SimulationService.SimulationEngine";

service SimulationEngineService {
  rpc RunSimulation (RunSimulationEngineRequest) returns (RunSimulationEngineResponse);
  rpc GetSimulationOverviewById (GetSimulationOverviewByIdRequest) returns (SimulationOverviewResponse);
  rpc GetAllSimulationOverviews (PagedRequest) returns (SimulationOverviewsPagedResponse);
  rpc GetSimulationStateById(GetSimulationStateByIdRequest) returns (SimulationStateResponse);
  rpc StopSimulationById(StopSimulationRequest) returns (StopSimulationResponse);
}