syntax = "proto3";

package SimPitchProtos.SimulationService.IterationResult;

import "SimulationService/IterationResult/requests.proto";
import "SimulationService/IterationResult/responses.proto";
import "SimulationService/commonTypes.proto";

option csharp_namespace = "SimPitchProtos.SimulationService.IterationResult";


service IterationResultService {
  rpc GetIterationResultById (IterationResultByIdRequest) returns (IterationResultByIdResponse);
  rpc GetIterationResultsBySimulationId (IterationResultsBySimulationIdRequest) returns (stream IterationResultsBySimulationIdResponse);
}