syntax = "proto3";

package SimPitchProtos.SportsDataService;

option csharp_namespace = "SimPitchProtos.SportsDataService";

// CountryDto
message CountryGrpc {
  string id = 1;
  string name = 2;
  string code = 3;
}

// StadiumDto
message StadiumGrpc {
  string id = 1;
  string name = 2;
  int32 capacity = 3;
}

// LeagueDto
message LeagueGrpc {
  string id = 1;
  string name = 2;
  string countryId = 3;
  int32 max_round = 4;
  repeated LeagueStrengthGrpc league_strengths = 5;
}
// LeagueStrengthDto
message LeagueStrengthGrpc {
  string id = 1;
  string league_id = 2;
  string season_year = 3;
  float strength = 4;
}
// CompetitionMembershipDto
message CompetitionMembershipGrpc {
  string id = 1;
  string team_id = 2;
  string league_id = 3;
  string season_year = 4;
}

// TeamDto
message TeamGrpc {
  string id = 1;
  string name = 2;
  CountryGrpc country = 3;
  StadiumGrpc stadium = 4;
  repeated CompetitionMembershipGrpc memberships = 5;
  string short_name = 6;
}
// LeagueRoundDto
message LeagueRoundGrpc{
  string id = 1;
  string league_id = 2;
  string season_year = 3;
  int32 round = 4;
}
// MatchRoundDto
message MatchRoundGrpc{
  string id = 1;
  string round_id = 2;
  string home_team_id = 3;
  string away_team_id = 4;
  optional int32 home_goals = 5;
  optional int32 away_goals = 6;
  optional bool is_draw = 7;
  bool is_played = 8;
}
// SeasonStatsDto
message SeasonStatsGrpc{
  string id = 1;
  string team_id = 2;
  string season_year = 3;
  string league_id = 4;
  int32 matches_played = 5;
  int32 wins = 6;
  int32 losses = 7;
  int32 draws = 8;
  int32 goals_for = 9;
  int32 goals_against = 10;
}