syntax = "proto3";

package SimPitchProtos.SimulationService;

option csharp_namespace = "SimPitchProtos.SimulationService";

message IterationResultGrpc {
    string id = 1;
    string simulation_id = 2;
    int32 iteration_index = 3;
    string start_date = 4;
    string execution_time = 5;
    string team_strengths = 6;
    string simulated_match_rounds = 7;
}

message SimulationParamsGrpc {
  string title = 1;
  repeated string season_years = 2;
  string league_id = 3;
  int32 iterations = 4;
  int32 seed = 5;
  optional string league_round_id = 6;
  optional bool create_scoreboard_on_complete_iteration = 7;
  optional int32 games_to_reach_trust = 8;
  optional float confidence_level = 9;
  optional float home_advantage = 10;
  optional float noise_factor = 11;
  string model = 12;
}

message SimulationOverviewGrpc{
  string id = 1;
  string created_date = 2;
  SimulationParamsGrpc simulation_params = 3;
  string league_strengths = 4;
  float prior_league_strength = 5;
}

message SimulationStateGrpc{
  string id = 1;
  string simulation_id = 2;
  int32 last_completed_iteration = 3;
  float progress_percent = 4;
  string state = 5;
  string updated_at = 6;
}

message SortingMethodGrpc{
  string sorting_option = 1;
  string order = 2;
}

message PagedRequestGrpc{
  int32 offset = 1;
  int32 limit = 2;
  SortingMethodGrpc sorting_method = 3;
}

message PagedResponseGrpc{
  int32 total_count = 1;
  string sorting_option = 2;
  string sorting_order = 3;
}