syntax = "proto3";

package SimPitchProtos.SportsDataService.Stadium;

import "google/protobuf/empty.proto";
import "SportsDataService/Stadium/requests.proto";
import "SportsDataService/Stadium/responses.proto";
import "SportsDataService/commonTypes.proto";

option csharp_namespace = "SimPitchProtos.SportsDataService.Stadium";

service StadiumService {
  rpc GetAllStadiums (google.protobuf.Empty) returns (StadiumListResponse);
  rpc GetStadiumById (StadiumByIdRequest) returns (StadiumGrpc);
  rpc CreateStadium (CreateStadiumRequest) returns (StadiumIdResponse);
}