syntax = "proto3";

package SimPitchProtos.StatisticsService;

option csharp_namespace = "SimPitchProtos.StatisticsService";

message ScoreboardGrpc {
    string id = 1;
    string simulation_id = 2;
    string simulation_result_id = 3;
    repeated ScoreboardTeamStatsGrpc scoreboard_teams = 4;
    float league_strength = 5;
    float prior_league_strength = 6;
    string created_at = 7;
}

message ScoreboardTeamStatsGrpc{
    string id = 1;
    string scoreboard_id = 2;
    string team_id = 3;
    int32 rank = 4;
    int32 points = 5;
    int32 match_played = 6;
    int32 wins = 7;
    int32 losses = 8;
    int32 draws = 9;
    int32 goals_for = 10;
    int32 goals_against = 11;
}