syntax = "proto3";

package SimPitchProtos.StatisticsService.Scoreboard;


option csharp_namespace = "SimPitchProtos.StatisticsService.Scoreboard";

message ScoreboardsByQueryRequest {
  string simulation_id = 1;
  optional string iteration_result_id = 2;
  optional bool withTeamStats = 3;
}

message CreateScoreboardsRequest{
  string simulation_id = 1;
  optional string iteration_result_id = 2;
}

message CreateScoreboardByIterationResultDataRequest{
  string simulation_overview_json = 1;
  string iteration_result_json = 2;
}

message CreateScoreboardByLeagueIdAndSeasonYearRequest{
  string league_id = 1;
  string season_year = 2;
}