syntax = "proto3";

package SimPitchProtos.StatisticsService.Scoreboard;


import "Scoreboard/requests.proto";
import "Scoreboard/responses.proto";

option csharp_namespace = "SimPitchProtos.StatisticsService.Scoreboard";

service ScoreboardService {
  rpc CreateScoreboards (CreateScoreboardsRequest) returns (ScoreboardsResponse);
  rpc GetScoreboardsByQuery (ScoreboardsByQueryRequest) returns (stream ScoreboardsResponse);
  rpc CreateScoreboardByIterationResultData (CreateScoreboardByIterationResultDataRequest) returns (CreateScoreboardByIterationResultDataResponse);
}